name: Run PHPStan in Laravel

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      # Code aus dem Repository klonen
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: intl, zip, mbstring
          ini-values: post_max_size=256M, max_execution_time=300
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # PHPStan ausführen
      - name: Run PHPStan
        run: |
          vendor/bin/phpstan analyse --memory-limit=1G
